### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by shahad-sb** [lahiruakmeemana/Fishcare#1]
Hi bro,
I was wondering if you could share the disease dataset with me, please.
I'm planning to train a ML model to detect the disease of fish for my final year project.

**Comment by lahiruakmeemana** [comment]
Hello,
As I mentioned in the readme, it was challenging to acquire fish disease images. I only collected 347 images, which were insufficient to train a CNN model. Therefore, instead of using a CNN for the disease detection I used a classification method, creating a dataset with symptoms as features and disease as target with the usage of collected images. If you think these will be useful for your project, you can download them from the following link.
https://drive.google.com/drive/folders/1owo7jtzBkTfbnrS4IhUUB2Tkb1Qm87sF?usp=sharing

**Comment by shahad-sb** [comment]
Thank you so much
